[package]
name = "gfx_basic"
version = "0.1.0"
authors = ["khanp"]

[dependencies]
sdl2 = { version = "*", features = ["bundled", "static-link"] }
gfx = "*"
gfx_window_sdl = "*"
cgmath = "0.16.1"

svgtess = {path = "../../", version = "*"}
