[package]
name = "svgtessEX"
version = "0.1.0"
authors = ["khanp"]

[dependencies]
sdl2 = { version = "*", features = ["bundled", "static-link"] }
gfx = "*"
gfx_window_sdl = "*"
cgmath = "0.16.1"
svgtess = {path = "../../", version = "*"}

[[bin]]
name = "gfx_basic"
path = "src/main.rs"